from app.infrastructure.repositories.admin import AdminRepository
from app.infrastructure.repositories.repositories import AppointmentRepository, CustomerRepository, LocationRepository, SchedulingRepository, ServiceRepository, StaffRepository, TenantRepository
